### ISSUE TITLE
Initialization error: db.dat is absent

### ISSUE THREAD

**Issue by GJDK** [regulaforensics/DocumentReader-iOS#15]
Hi @DmitrySmolyakov , 
I downloaded and added the db.dat to the Xcode project by "Add Files To project" option.

On successfully running the application, when i click the option, "DefaultModeViewController", Initialization process starts by downloading the database. But at last it is showing db.dat is absent.

Kindly help me on running the sample successfully. 

Thanks.

**Comment by GJDK** [comment]
Also sometimes am getting **Initialization error: db.dat is incorrect**

**Comment by DmitrySmolyakov** [comment]
Hello,

We have released new version yesterday, please make sure that you are use latest version 4.2.
Try to run pod update command

**Comment by GJDK** [comment]
Thanks @DmitrySmolyakov for the help. After running "pod update", the sample is running fine.

**Comment by DmitrySmolyakov** [comment]
Glad to help
