### ISSUE TITLE
Module compiled with Swift 5.0 cannot be imported by the Swift 4.2.1 compiler

### ISSUE THREAD

**Issue by fedorlarin0531** [regulaforensics/DocumentReader-iOS#17]
When I tried to use this framework with Xcode 10.1 and Swift 4.2.1, I am getting error as like this.
Module compiled with Swift 5.0 cannot be imported by the Swift 4.2.1 compiler

How can I use this framework with Swift 4.2.1?

**Comment by DmitrySmolyakov** [comment]
Hello, @fedorlarin0531!

The latest framework version supports only Swift 5.0. Please, specify previous version of DocumentReader, it have supported Swift 4.2.1:

pod 'DocumentReader', '4.2.1514'
