### ISSUE TITLE
dyld: Library not loaded: App Crash

### ISSUE THREAD

**Issue by fedorlarin0531** [regulaforensics/DocumentReader-iOS#18]
I just downloaded demo project and pod installed.

This is pod file content.

platform :ios, '9.0'

target 'DocumentReaderFullSwift-sample' do
  use_frameworks!
  pod 'DocumentReader', '4.2.1514'
end

When app launch, app crashing with this error log.

dyld: Library not loaded: @rpath/DocumentReaderCore.framework/DocumentReaderCore
  Referenced from: /private/var/containers/Bundle/Application/E7F47BA9-4084-4673-A637-7E14C8BD63C8/DocumentReaderFullSwift-sample.app/Frameworks/DocumentReader.framework/DocumentReader
  Reason: image not found

**Comment by DmitrySmolyakov** [comment]
You can't use our SDK without including at least one Core framework. More information you can find here: https://github.com/regulaforensics/DocumentReader-iOS#-how-to-build-demo-application

By default you can use 'DocumentReaderFull' core, please don't remove it from podfile. It uses Objective C inside, so it can be compiled with any version of Swift.
