### ISSUE TITLE
License step 2 fails: invalid date

### ISSUE THREAD

**Issue by fedorlarin0531** [regulaforensics/DocumentReader-iOS#19]
When I call `initilizeReader` method, I can get this error log.

Initialization...
License step 2 fails: invalid date
ERROR

And when I call `prepareCameraViewController` methods, returned vc value is nil.

this problem is for license?
If I get new extended license file, this problem will be fixed?

Looking forward to see your reply.
Regards.

**Comment by DmitrySmolyakov** [comment]
Yeah, exactly, your license has been expired. Without license you can't use SDK and can't create new CameraViewController instance.
