### ISSUE TITLE
Can not install pod

### ISSUE THREAD

**Issue by mingtai511** [regulaforensics/DocumentReader-iOS#2]

**Comment by mingtai511** [comment]
When I tried to install pod, I can not install pod.
I got this message.
[!] Unable to find a specification for `DocumentReaderMRZ`
Any hint?
Thanks

**Comment by DmitrySmolyakov** [comment]
@mingtai511 Try to run from terminal:
`pod repo update`

**Comment by mingtai511** [comment]
Solved
Thanks
