### ISSUE TITLE
Remove Regula DB

### ISSUE THREAD

**Issue by Serg-Pogrebnyak** [regulaforensics/DocumentReader-iOS#23]
Hi! How I can remove DB regula?

**Comment by DmitrySmolyakov** [comment]
Hello,

What do you mean? Can you provide more details about your workflow?

The database stores the documents' data. It's mandatory to have db.dat file if the type of the document, OCR zone information should be recognized. If MRZ, Barcode recognition or image cropping are used, there is no need to have the db.dat file.

You can find more information about the database here: https://docs.regulaforensics.com/ios/database.

**Comment by Serg-Pogrebnyak** [comment]
yeah I know about this, I use Regula SDK for register user, so I download Regula DB, and register user via scan passport information, when user successfully registered, I can remove Regula DB because in future I will not use it, howe I can do this?

**Comment by DmitrySmolyakov** [comment]
The database is unzipped along this path:
Library/Application Support/Regula/db/

You can remove this folder after you have finished work with our SDK. But don't forget to call prepareDatabase again before the next initialization of SDK. It will not work correctly without this step.
