### ISSUE TITLE
version 4.2 not working with XCode 11

### ISSUE THREAD

**Issue by mingxun** [regulaforensics/DocumentReader-iOS#25]
I just downloaded XCode 11 and tried to compile my project which has DocumentReader Version 4.2 and got a compiled error: Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: /Pods/DocumentReader/DocumentReader.framework/Modules/DocumentReader.swiftmodule/arm64.swiftmodule

Will you provide a version which compiled with XCode 11 soon?

**Comment by DmitrySmolyakov** [comment]
Hello @mingxun,

Please, use the latest one DocumentReader SDK version 5.0: https://github.com/regulaforensics/DocumentReader-iOS/releases/tag/v5.0

**Comment by mingxun** [comment]
I changed the pod to 5.0 and rebuild my project and got the same error: Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: <myProjectRootDir>/Pods/DocumentReader/DocumentReader.framework/Modules/DocumentReader.swiftmodule/arm64.swiftmodule. Is there anything I should check?

**Comment by vyakimchik** [comment]
Hello,

It seems that you are still using the SDK 4.2 as the latest version 5.0 uses Objective-C in order to avoid such issues. Try to run `pod update` inside your project folder or add the SDK (API and Core frameworks) manually to the project.

**Comment by mingxun** [comment]
You are right. I did the pod update. But the update was not successful which I did not notice. Not I fixed that error and update was done. Now I am getting different errors.  it is complaining about some methods are not there. Is there a guide on how to migrate from 4.2 to 5.0?

**Comment by vyakimchik** [comment]
The migration guide can be found here: https://docs.regulaforensics.com/ios/migration-guide.

**Comment by mingxun** [comment]
Got it, thanks. That fixed my issue

**Comment by vyakimchik** [comment]
Glad to be of help!
