### ISSUE TITLE
Can't get the values from Malaysian MyKad back images

### ISSUE THREAD

**Issue by coldmachine** [regulaforensics/DocumentReader-iOS#27]
Hello, is it possible? I am getting empty results. Using swift

` func handleResult(result: DocumentReaderResults?) {
     let size = result.textResult.fields.count
`
I can scan the card but the size of fields is always zero

Here is the sample image: [http://www.myunify.com.my/components/com_chronocontact/uploads/resident20150722095703_IC%20Back.jpg](url)

**Comment by vyakimchik** [comment]
Hello. Replied to email.
