### ISSUE TITLE
Capture button doesn't apper

### ISSUE THREAD

**Issue by olcayertas** [regulaforensics/DocumentReader-iOS#28]
Although I set it to show capture button it doesn't shown immediately:
`DocReader.shared.functionality.showCaptureButton = true`
It apperaers after 10 seconds.

**Comment by vyakimchik** [comment]
Hello. Yeah. We added 2 new options (`showCaptureButtonDelayFromDetect`, `showCaptureButtonDelayFromStart`) which indicate when the Capture Button has to be shown. More information can be found here: https://docs.regulaforensics.com/ios/custom-settings#buttons. Set value to 0 to display the Capture Button immediately:
`DocReader.shared.functionality.showCaptureButtonDelayFromStart = 0`
