### ISSUE TITLE
When i tried to test 'DocumentReaderCore', the app can not scan MRZ code

### ISSUE THREAD

**Issue by mingtai511** [regulaforensics/DocumentReader-iOS#3]

**Comment by mingtai511** [comment]
When i test  'DocumentReaderCore, the app didn't scan MRZ code
So I checked log, 
"License step 5 fails: no capabilities"
I introduced license file correctly.
Why the license fail issue occure?
Thanks

**Comment by DmitrySmolyakov** [comment]
@mingtai511, Try to recreate license key now. We add MRZ core recently, and if you create your key more then one week ago it just not support MRZ mode.
By the way, I'm check all this step right now and all working fine, please try.

**Comment by mingtai511** [comment]
OK, Thanks, I will try again now

**Comment by mingtai511** [comment]
By the way I can not create license key again with same bundle id,
Can you remove old license key?
Because the bundle id should not be changed because app was published
Thanks

**Comment by mingtai511** [comment]
OK, I solved issue,
Thanks
