### ISSUE TITLE
Add support for Mac Catalyst

### ISSUE THREAD

**Issue by olcayertas** [regulaforensics/DocumentReader-iOS#30]
We want to use[ Mac Catalyst](https://developer.apple.com/mac-catalyst/) to run our app on Mac OS X but Document Reader SDK does not support it. Related information can be foun in following article:

[How to build a Fat Framework that Includes Mac Catalyst Support](https://onesignal.com/blog/mac-catalyst-fat-framework/)

**Comment by ikliashchou** [comment]
Hello,

Desktop and mobile platforms are different from licensing point of view. Please contact us at support@regulaforensics.com and tell us a bit about your app and how we can help you with it.

**Comment by olcayertas** [comment]
We are considering getting license for it if we can develop a working and usable product. We have an iPhone app that can suppor iPad. Apple introduces a feature called Mac Catalyst whic makes iPad apps also beeing able to run on Mac OS X. Inorder to use Mac Catalyst we need Document Reader SDK to support it.

**Comment by olcayertas** [comment]
We already have a license for iOS. Can you provide a fat framework for experimenting?

**Comment by ikliashchou** [comment]
Please contact us at support@regulaforensics.com.
