### ISSUE TITLE
DocumentReaderGraphicResult doesn't return an image for a .gf_Portrait path.

### ISSUE THREAD

**Issue by bugrym** [regulaforensics/DocumentReader-iOS#32]
Test your demo project and my own with ur SDK and didn't get a portrait image, at the same time it works well in ur app from App Store. Every time I get a nil value. 
Try to get the portrait image in that way: 
`if let portraitImage = result.getGraphicFieldImageByType(fieldType: .gf_Portrait) {
            self.portraitImage = portraitImage
        }`

the same try with a document image and everything is fine:
`if let documentImage = result.getGraphicFieldImageByType(fieldType: .gf_DocumentImage) {
            self.portraitImage = documentImage
        }`

How can I handle this issue? 
best regards

**Comment by vyakimchik** [comment]
Hello. What scenario do you use? Please remember that it can't be received in scenarios like `Mrz`, `Locate` and so on.

**Comment by bugrym** [comment]
Thank a lot! It was the key point, cuz I had a "Mrz" scenario while I needed a "FullProcess" instead.
