### ISSUE TITLE
Есть ли либа упакованная в xcframework?

### ISSUE THREAD

**Issue by LavTeamProject** [regulaforensics/DocumentReader-iOS#39]
Добрый день!
Есть ли  DocumentReader упакованный в xcframework?
Нужна поддержка реальных девайсов, симулятора и чтобы все это работало на Apple M1

На текущий момент сборка на девайсе собирается и работает, на симуляторе ошибка (ноут на m1, на ноуте на Интере проблем нет):
building for iOS Simulator, but linking in dylib built for iOS, file '/Carthage/Build/iOS/DocumentReader.framework/DocumentReader' for architecture arm64

**Comment by vyakimchik** [comment]
Добрый день!

К сожалению, на данный момент нет. Мы сейчас занимаемся реализацией сброки данного типа фреймворка. Как только это будет реализовано, мы вам сообщим.

Спасибо!

**Comment by LavTeamProject** [comment]
> Добрый день!
> 
> К сожалению, на данный момент нет. Мы сейчас занимаемся реализацией сброки данного типа фреймворка. Как только это будет реализовано, мы вам сообщим.
> 
> Спасибо!

Благодарю за оперативный ответ.
А примерные сроки есть?

**Comment by vyakimchik** [comment]
Постараемся в течении двух недель это реализовать.
> А примерные сроки есть?

Да, верно.
> Немного уточню, в проекте в данный момент используются и обе имеют поддержку только Intel платформы.
> DocumentReader.framework
> DocumentReaderCore.framework

**Comment by LavTeamProject** [comment]
> Постараемся в течении двух недель это реализовать.
> 
> > А примерные сроки есть?
> 
> Да, верно.
> 
> > Немного уточню, в проекте в данный момент используются и обе имеют поддержку только Intel платформы.
> > DocumentReader.framework
> > DocumentReaderCore.framework

Добрый день!
Вышло ли обновление с поддержкой m1?
DocumentReader.framework
DocumentReaderCore.framework

Если уже да, то где можно скачать библиотеки?

**Comment by vyakimchik** [comment]
Здравствуйте! Да, версия фреймворки версии 5.7 собраны как xcframework, которые доступны через [CocoaPods](https://docs.regulaforensics.com/ios/how-to-add-the-sdk-to-the-project). Пример [Podfile](https://github.com/regulaforensics/DocumentReader-iOS/blob/master/Samples/Basic/DocumentReaderSwift-sample/Podfile).
