### ISSUE TITLE
DocumentReader was compiled on Swift3.1

### ISSUE THREAD

**Issue by mingtai511** [regulaforensics/DocumentReader-iOS#4]
I 'm using documentreader sdk on my project
My project was developed swift3.0
Today i updated xcode to 9.0
Then i got compile error 
"import DocumentReader"  DocumentReader was compiled on swift3.1, so not compatible on swift3.2
Can you update sdk on xcode9.0?
Thanks

**Comment by ikliashchou** [comment]
DocumentReader 2.4.0 already compiled with Swift 4. Please update pods.

**Comment by mingtai511** [comment]
OK, thanks
