### ISSUE TITLE
Build error on case sensitive apfs volume

### ISSUE THREAD

**Issue by akospalfi** [regulaforensics/DocumentReader-iOS#40]
There's a typo in the `RGLCustomization.h` header file which breaks the build on macOS systems where the root volume is case sensitive.

```
#import <UIKit/UIkit.h>
```

The `UIkit.h` should be `UIKit.h`

Please fix this typo if possible.

**Comment by vyakimchik** [comment]
Hello,

Thanks! The issue has been fixed. The fix will be available in the next Release version. We'll inform you once it's published.

**Comment by akospalfi** [comment]
Thank you so much!
