### ISSUE TITLE
TourchButton not hiding

### ISSUE THREAD

**Issue by nikolindima** [regulaforensics/DocumentReader-iOS#41]
after update pods. Installing DocumentReader 5.7.2075 (was 5.5.1910)
DocReader.shared.functionality.showTorchButton = false - stop working. button always visible

**Comment by vyakimchik** [comment]
Hi @nikolindima,

Have the issue been solved? Can we close the ticket? If not, could you please try to reproduce the issue on the latest release version that is 7.2? If the issue still happens, please let us know.
