### ISSUE TITLE
Trial license

### ISSUE THREAD

**Issue by mobileAI311** [regulaforensics/DocumentReader-iOS#42]
Hi.
Web portal for trial license doesn't work.
Buttons don't work there.
Can you please check it?
Thanks.

**Comment by DmitrySmolyakov** [comment]
Thank you for informing us, we are already working to fix that. I will keep you posted. 
Please write to our support, and our team will help you with creating the demo license key: support@regulaforensics.com

**Comment by DmitrySmolyakov** [comment]
@mobileAI311 The issue has been fixed. Thanks!
