### ISSUE TITLE
App crashing on  initializeReader(config: Config(license: license), completion: completion)

### ISSUE THREAD

**Issue by Zulqurnain24** [regulaforensics/DocumentReader-iOS#44]
Hi,
App is crashing on "initializeReader(config: Config(license: license), completion: completion)" after I updated the db.dat file in iOS

giving this log:
malloc: can't allocate region
:*** mach_vm_map(size=8223735808, flags: 100) failed (error code=3)
 malloc: *** set a breakpoint in malloc_error_break to debug
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
terminating with uncaught exception of type std::bad_alloc: std::bad_alloc

What can be the possible cause?

**Comment by DmitrySmolyakov** [comment]
Hello @Zulqurnain24. This issue is related to the incompatibilities of the new db.dat and the current release version. Please contact support@regulaforensics.com to get new updated frameworks beta versions.
