### ISSUE TITLE
Swift4.1 doesnt support

### ISSUE THREAD

**Issue by yang511** [regulaforensics/DocumentReader-iOS#5]
pod 'DocumentReader'
pod 'DocumentReaderMRZ'

When i try pod update, i got this error
Please check screenshot

http://prntscr.com/iyk07m

How can i solve it?
Please let me know
Thanks

**Comment by yang511** [comment]
I need pod for swift 4.1 or swift3.3
Where can i find it?
Thanks

**Comment by DmitrySmolyakov** [comment]
Pod 'DocumentReader' updated, please use 3.2.0 version

**Comment by yang511** [comment]
Hello
Yesterday I did pod updated, but i got error "Pod was compiled swift 4.0.3"
But now swift 4.1 version occured.
Did you check your pod on new xcode?

**Comment by DmitrySmolyakov** [comment]
Hello @yang511,

Please check the latest update for demo app. 3.2.0 version now required iOS 9.0 version, I think exactly because of that you didn't get new 'DocumentReader' pod version. Please verify that you are using 3.2.0 version.
