### ISSUE TITLE
[BR] DocumentReaderFullRFID pod conflict with onnxruntime-objc pod 

### ISSUE THREAD

**Issue by pksa** [regulaforensics/DocumentReader-iOS#64]
**Bug Description**

I have downloaded a sample application and added another pod `onnxruntime-objc` from ONNXRuntime in podfile and run the application. After that, I added object detection functionality using onnxruntime pod methods but got **EXC_BAD_ACCESS** error. For testing purposes I removed the `DocumentReaderFullRFID` pod then It was working fine. So I  believe `DocumentReaderFullRFID` and `onnxruntime-objc` pods are conflicting with each other.

**Steps To Reproduce**
1. Download the project from this link(https://drive.google.com/file/d/1kBLsTZrBdUw9NyYHMHKM4-COM7RrjBwp/view?usp=share_link)
2. Install pod
3. Add regula license 
4. After running the application, Click on the **ORT** button it will show **EXC_BAD_ACCESS** error

**Expected behavior**

Let me know which version of onnxruntime you are using in DocumentReaderFullRFID, So I can use the same version and maybe an issue will be resolved.
I want to use the ONNXRuntime library anyhow because I want to process images as well as Document scans. 

**Screenshots**

![Screenshot 2023-04-05 at 11 32 01 AM](https://user-images.githubusercontent.com/74169429/229999046-92d8ecbe-47a8-4880-8fa5-76445f12ab2f.png)

**Environment:**
 - Device: iPhone 8
 - OS version: 16.3.1
 - Xcode 14.2

Let me know if any queries 

Thanks!

**Comment by edgchen1** [comment]
Looks like there is a shared library, DocumentReaderCore:
```
% file Pods/DocumentReaderFullRFID/DocumentReaderCore.xcframework/ios-arm64_x86_64-simulator/DocumentReaderCore.framework/DocumentReaderCore
Pods/DocumentReaderFullRFID/DocumentReaderCore.xcframework/ios-arm64_x86_64-simulator/DocumentReaderCore.framework/DocumentReaderCore: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [arm64]
Pods/DocumentReaderFullRFID/DocumentReaderCore.xcframework/ios-arm64_x86_64-simulator/DocumentReaderCore.framework/DocumentReaderCore (for architecture x86_64):        Mach-O 64-bit dynamically linked shared library x86_64
Pods/DocumentReaderFullRFID/DocumentReaderCore.xcframework/ios-arm64_x86_64-simulator/DocumentReaderCore.framework/DocumentReaderCore (for architecture arm64): Mach-O 64-bit dynamically linked shared library arm64
```

which exports symbol _OrtGetApiBase.
```
% nm -g Pods/DocumentReaderFullRFID/DocumentReaderCore.xcframework/ios-arm64_x86_64-simulator/DocumentReaderCore.framework/DocumentReaderCore | grep OrtGetApiBase
0000000000b0c550 T _OrtGetApiBase
```

The static library in onnxruntime-c also has a symbol with the same name.

**Comment by vyakimchik** [comment]
Hello. Please have a look at the new version - 6.8. The issue was fixed there. Thank you!

**Comment by vyakimchik** [comment]
Hi @pksa,

Have the issue been solved? Can we close the ticket?
