### ISSUE TITLE
[FR] Add SPM support

### ISSUE THREAD

**Issue by Deitsch** [regulaforensics/DocumentReader-iOS#68]
Since SPM has now been around for quite a while, adding SPM support is clearly the way Apple is going with dependencies. Are there plans allow to use Regula with the native package manager for iOS?

**Comment by vyakimchik** [comment]
Hi @Deitsch!

Thank you for your interest in SPM support! We're thrilled to hear that you're interested in it.

It's indeed on our roadmap, and we're actively working on bringing it to our users. While I can't provide a specific timeframe at the moment, rest assured that we will keep you updated on our progress. Your patience is greatly appreciated!

**Comment by vyakimchik** [comment]
Hi @Deitsch,

We added support of SPM. Please see the guide how to install packages here: https://docs.regulaforensics.com/develop/doc-reader-sdk/mobile/getting-started/installation/ios/#swift-package-manager-spm
