### ISSUE TITLE
Customization scan view

### ISSUE THREAD

**Issue by btrn** [regulaforensics/DocumentReader-iOS#9]
Hi,

I need to customization the scan view texts like "searching for a document..." to translate to another languages.

is it posible?

**Comment by DmitrySmolyakov** [comment]
Hello,

Unfortunately, we don't support custom localization now. It will be added in next release version. You could change this status or disable it:

docReaderInstance.customization.status = "Your status"
docReaderInstance.customization.showHintMessages = false

**Comment by btrn** [comment]
ok, thanks
